name: master-project
services:
  rabbitmq-server:
    user: "1000:1000"
    cap_drop:
      - "ALL"
    security_opt:
      - "no-new-privileges"
    image: rabbitmq:3-management-alpine
  otel-generator:
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.104.0
    command: "traces --otlp-endpoint otel-collector:4317 --otlp-insecure --duration 5s"
    restart: on-failure
    depends_on:
      - otel-collector
  otel-collector:
    build:
      context: go
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq-server
      - trace-receiver
  trace-receiver:
    user: "1000:1000"
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    build:
      context: java
      dockerfile: ./trace-receiver/Dockerfile
      args:
        JAR_FILE: /java/trace-receiver/target/trace-receiver*.jar
        ARTIFACT_ID: :trace-receiver
    restart: on-failure
    depends_on:
      - rabbitmq-server
networks:
  default:
    name: "master-project-network"