name: db-init
services:
  db-initializer:
    build:
      context: java/db-initializer
      dockerfile: ./Dockerfile
      args:
        ARTIFACT_ID: db-initializer
    restart: on-failure
networks:
  default:
    name: "master-project-network"
    external: true
