spring:
  application:
    name: trace-receiver
  rabbitmq:
    port: 5672
    host: rabbitmq-server
open_telemetry:
  exporter:
    routing_key:
      traces: otlp_spans
      metrics: otlp_metrics
      logs: otlp_logs
otel_to_probd:
  routing_key:
    out:
      resource_spans_queue: resource-spans-queue
      trace_spans_queue: trace-spans-queue
      jaeger-trace-queue: jaeger-trace-queue
      jaeger_trace_spans_list_queue: jaeger-trace-spans-list-queue
    in:
      declare: probd-result-queue
      span_trees: span-tree-result-queue
server:
  port: 4020
db-service:
  base-url: http://db-service:4242/v1
  traces:
    url: /traces
    endpoints:
      data-overview: /data-overview
      source: /source
  spans:
    url: /spans
    endpoints:
      sourceDetails: /source-details
  declare:
    url: /declare
  prob-declare:
    url: /prob-declare
  prob-declare-to-trace:
    url: /prob-declare-to-trace
  canonized-span-tree:
    url: /canonized-span-tree
