spring:
  application:
    name: trace-transformer
  rabbitmq:
    port: 5672
    host: rabbitmq-server

open_telemetry:
  exporter:
    routing_key:
      traces: otlp_spans
      metrics: otlp_metrics
      logs: otlp_logs

otel_to_probd:
  routing_key:
    out: otel-to-probd-queue
    in: probd-result-queue

server:
  port: 4020
#  servlet:
#    context-path: /trace-receiver/