exporters:
    otlphttp:
        endpoint: http://trace-receiver:4020
        compression: none
        encoding: json
receivers:
    otlp:
        protocols:
#            grpc:
#                endpoint: 0.0.0.0:4317
            http:
                endpoint: otelcol:4318
processors:
    batch:
extensions:
    health_check:
    pprof:
    zpages:
service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp]