
dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.104.0
#extensions:
#  - gomod:
#      github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding v0.104.0
# exporter that sends our traces to a RabbitMQ-Queue so we can gather it with a client for further processing
exporters:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/rabbitmqexporter v0.104.0
processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.104.0
receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.104.0
