exporters:
  rabbitmq:
      connection:
        endpoint: amqp://rabbitmq-server:5672
        auth:
          plain:
            username: guest
            password: guest
      #encoding_extension: otlp_encoding/rabbitmq
#extensions:
#  otlp_encoding/rabbitmq:
#    protocol: otlp_json
processors:
  batch:
    send_batch_max_size: 10000
    timeout: 0s
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]