exporters:
  rabbitmq:
    connection:
      endpoint: amqp://rabbitmq-server:5672
      auth:
        plain:
          username: guest
          password: guest
#    encoding_extension: otlp_encoding
#extensions:
#  otlp_encoding:
#    protocol: otlp_json
processors:
  batch:
    send_batch_max_size: 10000
    timeout: 0s
receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318
#      grpc:
#        endpoint: otel-collector:4317
service:
#  extensions: [otlp_encoding]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [rabbitmq]
