dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.104.0
# exporter that sends our traces to a RabbitMQ-Queue so we can gather it with a client for further processing
exporters:
  - gomod:
      github.com/open-telemetry/opentelemetry-trace_collector-contrib/exporter/rabbitmqexporter v0.104.0
  - gomod:
      go.opentelemetry.io/trace_collector/exporter/debugexporter v0.104.0
  - gomod:
      go.opentelemetry.io/trace_collector/exporter/otlpexporter v0.104.0

processors:
  - gomod:
      go.opentelemetry.io/trace_collector/processor/batchprocessor v0.104.0

receivers:
  - gomod:
      go.opentelemetry.io/trace_collector/receiver/otlpreceiver v0.104.0
